### ISSUE TITLE
[Targeting Android 12] Push notifications not appearing.

### ISSUE THREAD

**Issue by calvarez-ov** [CleverTap/clevertap-android-sdk#202]
**Describe the bug**

Summary:
CleverTap's `PushProviders.triggerNotification()` needs to declare whether the `PendingIntent` is mutable or not, otherwise notifications don't appear in an app **targeting** Android 12, on an Android 12 emulator/device.

Details:
We're following the documentation for custom [push notification handling](https://developer.clevertap.com/docs/android#section-custom-android-push-notifications-handling).

We have our service as in the doc, except we added the `android:exported="false"` attribute to be [compliant with android 12](https://developer.android.com/about/versions/12/behavior-changes-12#exported). We set it to "false" based on [firebase documentation](https://firebase.google.com/docs/cloud-messaging/android/client?hl=uk#manifest):
```xml
<service
    android:exported="false"
    android:name="com.your.package.MyFcmMessageListenerService">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
    </intent-filter>
</service>
```

Our `MyFcmMessageListenerService` has this:
```kotlin
class MyFcmMessageListenerService : FirebaseMessagingService() {
    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)
        if (remoteMessage.data.isNotEmpty()) {
            // If we're notified first, make sure clevertap is notified if it's meant for clevertap
            // https://support.clevertap.com/docs/android/custom-push-notifications-handling.html
            val extras = mapToExtras(remoteMessage.data)
            val info = CleverTapAPI.getNotificationInfo(extras)
            if (info.fromCleverTap) {
                CleverTapAPI.createNotification(applicationContext, extras)
            } else {
                // This is not the push you're looking for...
            }
        }
    }

```

If we change our app to have `targetSdkVersion` and `compileSdkVersion` to `31`, then we have the following problem:

**To Reproduce**
1. Go to the CleverTap console
2. Find your user
3. Click on "Send push" next to the bell 🔔 
4. Fill out everything, including the notification channel, and send the push

**Expected behavior**
* Expected behavior: On the device, the notification appears
* Actual behavior: On the device, the notification doesn't appear, and there's a warning in logcat about targeting Android 12

**Screenshots/Logs**
```
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z: Couldn't render notification:
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z: java.lang.IllegalArgumentException: lifeisbetteron.com.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at com.clevertap.android.sdk.pushnotification.PushProviders.triggerNotification(PushProviders.java:949)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at com.clevertap.android.sdk.pushnotification.PushProviders.access$200(PushProviders.java:73)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at com.clevertap.android.sdk.pushnotification.PushProviders$1.call(PushProviders.java:185)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at com.clevertap.android.sdk.pushnotification.PushProviders$1.call(PushProviders.java:154)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at com.clevertap.android.sdk.task.Task$1.run(Task.java:209)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at com.clevertap.android.sdk.task.PostAsyncSafelyExecutor$1.run(PostAsyncSafelyExecutor.java:45)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-11 17:28:26.506 14504 14611 D CleverTap:TEST-7KK-RW7-6Z5Z:   at java.lang.Thread.run(Thread.java:920)
```

So: our service **is** being called, so there's no issue with the `<service>` declaration in the manifest. The issue appears to be with the `PendingIntent` missing the mutability flag. See the documentation below.

**Environment (please complete the following information):**
 - Device: Android emulator
 - OS: Android 12
 - CleverTap SDK Version 4.2.0
 - Android Studio Version Arctic fox 2020.3.1 Patch 1
 - Android Gradle Plugin 7.0.2

**Additional context**
Here's Google documentation about supporting android 12, for `PendingIntent`: https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

Note: There's no issue, even on an Android 12 device/emulator, if our app continues to **target** android 11 (api level 30)

**Comment by darshanclevertap** [comment]
@calvarez-ov We have released the new version (4.3.0) of the CleverTap Android SDK today. This issue has been fixed in it.

**Comment by manishkummar21** [comment]
@darshanclevertap After updating the SDK to 4.4.0, I got the deprecation warning on **CTNotificationIntentService** Class. 

**Are any changes I need to do?**

**Comment by piyush-kukadiya** [comment]
@manishkummar21 , no change is required but do not remove it as it still getting used for OS <= Android 11. Please check this https://github.com/CleverTap/clevertap-android-sdk/blob/master/clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/CTNotificationIntentService.java#L34

**Comment by manishkummar21** [comment]
@piyush-kukadiya @darshanclevertap 

In the Current Production App, we are using the SDK version is 3.9.1. we are using the custom Firebase Message Service, HmsMessageService, PushMessageReceiver

**Android Manifest Looks like this**

        <service android:name=".MyFcmListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service
            android:name=".HuaweiListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.huawei.push.action.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        
        <receiver
            android:name=".XioamiPushMessageReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.xiaomi.mipush.RECEIVE_MESSAGE" />
            </intent-filter>
            <intent-filter>
                <action android:name="com.xiaomi.mipush.MESSAGE_ARRIVED" />
            </intent-filter>
            <intent-filter>
                <action android:name="com.xiaomi.mipush.ERROR" />
            </intent-filter>
        </receiver>

In each class we calling the  CleverTapAPI.createNotification(getApplicationContext(), extras) on Message Received.

Now we planning to update SDK to  4.4.0. **Any changes I need to do for the above Classes?** Please confirm ASAP

**Comment by manishkummar21** [comment]
One More Question 

In 3.9.1 there is a function **registerBooleanVariable**. I couldn't similar method after updating to 4.4.0

**Comment by piyush-kukadiya** [comment]
@manishkummar21 I would suggest to have a look at changelog from 3.9.1 to 4.4.0 for any breaking changes https://github.com/CleverTap/clevertap-android-sdk/blob/master/CHANGELOG.md

**Comment by manishkummar21** [comment]
> @manishkummar21 I would suggest to have a look at changelog from 3.9.1 to 4.4.0 for any breaking changes https://github.com/CleverTap/clevertap-android-sdk/blob/master/CHANGELOG.md

OK

**Comment by manishkummar21** [comment]
@piyush-kukadiya @darshanclevertap After updating the SDK to 4.4.0 notification is not coming.

Testing Steps
1. After User Logged into our Application 
2. In the clever tap dashboard I searched the user by email.
3. Clicked on Send Push.

<img width="1472" alt="Screenshot 2022-01-25 at 3 43 10 PM" src="https://user-images.githubusercontent.com/16359663/150957421-3a1cb246-8a3a-454c-8334-6d7cfb3627f2.png">

But Notification not received on our Custom FirebaseMessagingService

**Note:- Same Step We tried on 3.9.1 is the previous SDK version Notification is received**

**Comment by piyush-kukadiya** [comment]
@manishkummar21 Can you turn on VERBOSE logging and share notification related logs? It will help to identify why it's not getting rendered.

**Comment by manishkummar21** [comment]
> @manishkummar21 Can you turn on VERBOSE logging and share notification related logs? It will help to identify why it's not getting rendered.

Sure

**Comment by manishkummar21** [comment]
D/CleverTap:TEST-5W5-797-K95Z: Send queue contains 9 items: [{"g":"__3cebe3741cb045659cc2f80074d8d2f1","type":"meta","af":{"Build":"282","Version":"5.2.46","OS Version":"11","SDK Version":40400,"Make":"samsung","Model":"SM-M315F","Carrier":"JIO 4G","useIP":false,"OS":"Android","wdt":2.57,"hgt":5.07,"dpi":420,"dt":1,"abckt":"active","lib":"Segment-Android","cc":"in"},"id":"TEST-5W5-797-K95Z","tk":"TEST-aca-505","l_ts":1643109948,"f_ts":1643107765,"ct_pi":"Email,Identity","ddnd":false,"rtl":[],"rct":0,"ait":0,"frs":true,"arp":{"sv":40400,"dh":-1288373694,"wdt":2,"d_ts":1643109937,"hgt":5,"av":"5.2.46","v":1,"e_ts":0,"j_n":"ZmxnewEG","i_n":"ZmxnewEG","r_ts":1643109950,"id":"5W5-797-K95Z","k_n":"[ \"manish1620250122@upgrad.com\" , \"ef37c8ce6b19aff648c178b0d3afc6bb\" , \"665571\"]","j_s":"{ }"},"imp":0,"tlc":[]}, {"evtName":"App Launched","evtData":{"Build":"282","Version":"5.2.46","OS Version":"11","SDK Version":40400,"Make":"samsung","Model":"SM-M315F","Carrier":"JIO 4G","useIP":false,"OS":"Android","wdt":2.57,"hgt":5.07,"dpi":420,"dt":1,"abckt":"active","cc":"in"},"s":1643110070,"pg":2,"type":"event","ep":1643110070,"f":false,"lsl":4,"pai":"****","dsync":true},{"evtName":"wzrk_fetch","evtData":{"t":1},"s":1643110070,"pg":2,"type":"event","ep":1643110070,"f":false,"lsl":4,"dsync":false},{"data":{"action":"register","id":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6NjM2MDIyMzUxNjA1OmFuZHJvaWQ6YTJiOTlmOGVkNDBiMjUwOSIsImV4cCI6MTY0MzcxMjUzOSwiZmlkIjoiZkJ1MDl5TVFTNk9fNWVpODZXT2dOcSIsInByb2plY3ROdW1iZXIiOjYzNjAyMjM1MTYwNX0.AB2LPV8wRAIgNb0sswfZcYKmH_VL882Yo1--qBKTI4C3vO1xAhbUkGQCIGFXi_-2feWGk292Dzr0dOC7t7NwRhOcF_w8uYFKwShp","type":"fcm"},"s":1643110070,"pg":2,"type":"data","ep":1643110070,"f":false,"lsl":4,"dsync":false},{"data":{"action":"register","id":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6NjM2MDIyMzUxNjA1OmFuZHJvaWQ6YTJiOTlmOGVkNDBiMjUwOSIsImV4cCI6MTY0MzcxMjUzOSwiZmlkIjoiZkJ1MDl5TVFTNk9fNWVpODZXT2dOcSIsInByb2plY3ROdW1iZXIiOjYzNjAyMjM1MTYwNX0.AB2LPV8wRAIgNb0sswfZcYKmH_VL882Yo1--qBKTI4C3vO1xAhbUkGQCIGFXi_-2feWGk292Dzr0dOC7t7NwRhOcF_w8uYFKwShp","type":"fcm"},"s":1643110070,"pg":2,"type":"data","ep":1643110070,"f":false,"lsl":4,"dsync":false},{"data":{"action":"register","id":"fBu09yMQS6O_5ei86WOgNq:APA91bHQBD8N5gsYneAZtvWE4dR3hCl7WM4HQf0a0qC3lUeWSFFQm0ZMGSprfT0ELeAW6ORkcGj02RvTN84HEVS9hTzYN5QgyxfxWSEknOaAmJyg1uh1tEUxdDytH7H4JpQHkW9OM_Ni","type":"fcm"},"s":1643110070,"pg":2,"type":"data","ep":1643110070,"f":false,"lsl":4,"dsync":false},{"evtName":"app_start","evtData":{"app_instance_id":"","platform":"Android","devicetype":"APP","manufacturer":"samsung","brand":"samsung","model":"SM-M315F","width":1080,"height":2131,"platform_version":"30","upgrad_app_version":"5.2.46","logged_in_flag":"true","paid_user":"false","enrollments":"","country":"United States","experiment":"no_email_variant1_version | signup_eligibility_step_variant_version | ProgramRecommendor_variant1","network_type":"WIFI","app_session_id":"$e5ad774d-0ea9-440b-9c65-5d05bdcfc585","activity":"start"},"s":1643110070,"pg":2,"type":"event","ep":1643110070,"f":false,"lsl":4,"dsync":false},{"evtName":"page_loaded","evtData":{"app_instance_id":"","platform":"Android","devicetype":"APP","manufacturer":"samsung","brand":"samsung","model":"SM-M315F","width":1080,"height":2131,"platform_version":"30","upgrad_app_version":"5.2.46","logged_in_flag":"true","paid_user":"false","enrollments":"","country":"United States","experiment":"no_email_variant1_version | signup_eligibility_step_variant_version | ProgramRecommendor_variant1","network_type":"WIFI","app_session_id":"$23105772-169f-439f-943b-6cc140747e64","page_url":"\/onboarding_screen\/","page_category":"onboarding_screen","page_title":"onboarding_screen","program_package_key":"onboarding_screen","deeplink_URI":""},"s":1643110070,"pg":2,"type":"event","ep":1643110070,"f":false,"lsl":4,"dsync":false},{"evtName":"Application Opened","evtData":{"version":"5.2.46","build":"282","from_background":false},"s":1643110070,"pg":2,"
2022-01-25 16:57:51.740 27278-4038/**** D/CleverTap:TEST-5W5-797-K95Z: type":"event","ep":1643110070,"f":false,"lsl":4,"dsync":false},{"evtName":"app_start","evtData":{"app_instance_id":"","platform":"Android","devicetype":"APP","manufacturer":"samsung","brand":"samsung","model":"SM-M315F","width":1080,"height":2131,"platform_version":"30","upgrad_app_version":"5.2.46","logged_in_flag":"true","paid_user":"false","enrollments":"","country":"United States","experiment":"no_email_variant1_version | signup_eligibility_step_variant_version | ProgramRecommendor_variant1","network_type":"WIFI","app_session_id":"$23105772-169f-439f-943b-6cc140747e64","activity":"resume"},"s":1643110070,"pg":2,"type":"event","ep":1643110070,"f":false,"lsl":4,"dsync":false}]
2022-01-25 16:57:51.741 27278-4038/**** D/CleverTap:TEST-5W5-797-K95Z: Sending queue to: https://eu1.clevertap-prod.com/a1?os=Android&t=40400&z=TEST-5W5-797-K95Z&ts=1643110071
2022-01-25 16:57:51.742 27278-4038/**** I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2022-01-25 16:57:51.743 27278-4038/**** I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2022-01-25 16:57:52.307 27278-4216/**** W/ad.student.tes: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist-max-q,core-platform-api, reflection, denied)
2022-01-25 16:57:52.307 27278-4216/**** W/ad.student.tes: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->getAlpnSelectedProtocol()[B (greylist-max-q, reflection, denied)
2022-01-25 16:57:52.691 27278-27278/**** E/Intercom: Failed to register or update user: {"type":"error.list","request_id":"0006l63fp675e0vuuva0","errors":[{"code":"hmac_mismatch","message":"Failed Identity Verification check"}]}
2022-01-25 16:57:53.832 27278-4038/**** V/CleverTap: Getting domain from header - null
2022-01-25 16:57:53.834 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Trying to process response: { "arp" : { "k_n" : "[ \"manish1620250122@upgrad.com\" , \"ef37c8ce6b19aff648c178b0d3afc6bb\" , \"665571\"]" , "j_n" : "ZmxnewEG" , "i_n" : "ZmxnewEG" , "d_ts" : 1643110070 , "dh" : 852114760 , "v" : 1 , "j_s" : "{ }" , "id" : "5W5-797-K95Z" , "e_ts" : 0 , "d_e" : [ ] , "r_ts" : 1643110075 , "wdt" : 2.57 , "hgt" : 5.07 , "av" : "5.2.46" , "sv" : 40400} , "imc" : 1 , "imp" : 10 , "pushamp_notifs" : { "list" : [ ] , "ack" : true , "pf" : 240}}
2022-01-25 16:57:53.835 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: InApp: Processing response
2022-01-25 16:57:53.835 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: InApp: Response JSON object doesn't contain the inapp key, failing
2022-01-25 16:57:53.837 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: New ARP Key = ARP:TEST-5W5-797-K95Z:__3cebe3741cb045659cc2f80074d8d2f1
2022-01-25 16:57:53.839 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: ARP update for key d_e rejected (invalid data type)
2022-01-25 16:57:53.841 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Stored ARP for namespace key: ARP:TEST-5W5-797-K95Z:__3cebe3741cb045659cc2f80074d8d2f1 values: {"k_n":"[ \"manish1620250122@upgrad.com\" , \"ef37c8ce6b19aff648c178b0d3afc6bb\" , \"665571\"]","j_n":"ZmxnewEG","i_n":"ZmxnewEG","d_ts":1643110070,"dh":852114760,"v":1,"j_s":"{ }","id":"5W5-797-K95Z","e_ts":0,"d_e":[],"r_ts":1643110075,"wdt":2.57,"hgt":5.07,"av":"5.2.46","sv":40400}
2022-01-25 16:57:53.843 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Inbox: Processing response
2022-01-25 16:57:53.843 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Inbox: Response JSON object doesn't contain the inbox key
2022-01-25 16:57:53.843 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Processing pushamp messages...
2022-01-25 16:57:53.844 27278-4038/**** V/CleverTap: Ping frequency received - 240
2022-01-25 16:57:53.844 27278-4038/**** V/CleverTap: Stored Ping Frequency - 240
2022-01-25 16:57:53.845 27278-4038/**** V/CleverTap: Received ACK -true
2022-01-25 16:57:53.864 27278-4038/**** V/CleverTap: Updating RTL values...
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Processing Display Unit items...
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: DisplayUnit : JSON object doesn't contain the Display Units key
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Processing Feature Flags response...
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Feature Flag : JSON object doesn't contain the Feature Flags key
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Processing Product Config response...
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Product Config : JSON object doesn't contain the Product Config key
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Processing GeoFences response...
2022-01-25 16:57:53.865 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Geofences : JSON object doesn't contain the Geofences key
2022-01-25 16:57:53.866 27278-4038/**** I/CleverTapResponse: Done processing response!
2022-01-25 16:57:53.868 27278-4038/**** D/CleverTap:TEST-5W5-797-K95Z: Queue sent successfully
2022-01-25 16:57:53.868 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Returning Queued events
2022-01-25 16:57:53.915 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: getCachedGUIDs:[{"Email_manish1620250122@upgrad.com":"__3cebe3741cb045659cc2f80074d8d2f1","Identity_665571":"__3cebe3741cb045659cc2f80074d8d2f1","Identity_ef37c8ce6b19aff648c178b0d3afc6bb":"__3cebe3741cb045659cc2f80074d8d2f1"}]
2022-01-25 16:57:53.915 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: getCachedIdentityKeysForAccount:Email,Identity
2022-01-25 16:57:53.915 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: isLegacyProfileLoggedIn:false
2022-01-25 16:57:53.915 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: getCachedIdentityKeysForAccount:Email,Identity
2022-01-25 16:57:53.916 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: ConfigurableIdentityRepoPrefIdentitySet [Email,Identity]
2022-01-25 16:57:53.916 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: ConfigurableIdentityRepoConfigIdentitySet []
2022-01-25 16:57:53.916 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: ConfigurableIdentityRepoNo error found while comparing [Pref:Email,Identity], [Config:]
2022-01-25 16:57:53.916 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: ConfigurableIdentityRepoIdentity Set activated from Pref[Email,Identity]
2022-01-25 16:57:53.916 27278-4038/**** V/CleverTap:[:ON_USER_LOGIN:TEST-5W5-797-K95Z]: Repo provider: ConfigurableIdentityRepo
2022-01-25 16:57:53.916 27278-4038/**** V/CleverTap:[:PushProvider:TEST-5W5-797-K95Z]:  [PushType:FCM] getting Cached Token - fBu09yMQS6O_5ei86WOgNq:APA91bHQBD8N5gsYneAZtvWE4dR3hCl7WM4HQf0a0qC3lUeWSFFQm0ZMGSprfT0ELeAW6ORkcGj02RvTN84HEVS9hTzYN5QgyxfxWSEknOaAmJyg1uh1tEUxdDytH7H4JpQHkW9OM_Ni
2022-01-25 16:57:53.927 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: New ARP Key = ARP:TEST-5W5-797-K95Z:__3cebe3741cb045659cc2f80074d8d2f1
2022-01-25 16:57:53.928 27278-4038/**** V/CleverTap:TEST-5W5-797-K95Z: Fetched ARP for namespace key: ARP:TEST-5W5-797-K95Z:__3cebe3741cb045659cc2f80074d8d2f1 values: {sv=40400, dh=852114760, wdt=2, d_ts=1643110070, hgt=5, av=5.2.46, v=1, e_ts=0, j_n=ZmxnewEG, i_n=ZmxnewEG, r_ts=1643110075, id=5W5-797-K95Z, k_n=[ "manish1620250122@upgrad.com" , "ef37c8ce6b19aff648c178b0d3afc6bb" , "665571"], j_s={ }}
2022-01-25 16:57:53.928 27278-4038/**** V/CleverTap: Attaching InAppFC to Header
2022-01-25 16:57:53.931 27278-4038/**** D/CleverTap:TEST-5W5-797-K95Z: Send queue contains 3 items: [{"g":"__3cebe3741cb045659cc2f80074d8d2f1","type":"meta","af":{"Build":"282","Version":"5.2.46","OS Version":"11","SDK Version":40400,"Make":"samsung","Model":"SM-M315F","Carrier":"JIO 4G","useIP":false,"OS":"Android","wdt":2.57,"hgt":5.07,"dpi":420,"dt":1,"abckt":"active","lib":"Segment-Android","cc":"in"},"id":"TEST-5W5-797-K95Z","tk":"TEST-aca-505","l_ts":1643110071,"f_ts":1643107765,"ct_pi":"Email,Identity","ddnd":false,"rtl":[],"rct":0,"ait":0,"frs":false,"arp":{"sv":40400,"dh":852114760,"wdt":2,"d_ts":1643110070,"hgt":5,"av":"5.2.46","v":1,"e_ts":0,"j_n":"ZmxnewEG","i_n":"ZmxnewEG","r_ts":1643110075,"id":"5W5-797-K95Z","k_n":"[ \"manish1620250122@upgrad.com\" , \"ef37c8ce6b19aff648c178b0d3afc6bb\" , \"665571\"]","j_s":"{ }"},"imp":0,"tlc":[]}, {"profile":{"Email":"manish1620250122@upgrad.com","Identity":665571,"Name":"Mmk","Carrier":"JIO 4G","cc":"in","tz":"Asia\/Kolkata"},"s":1643110070,"pg":1,"type":"profile","ep":1643110070,"f":false,"lsl":4,"dsync":true},{"profile":{"Email":"manish1620250122@upgrad.com","Identity":665571,"Name":"Mmk","Carrier":"JIO 4G","cc":"in","tz":"Asia\/Kolkata"},"s":1643110070,"pg":1,"type":"profile","ep":1643110070,"f":false,"lsl":4,"dsync":true},{"profile":{"anonymousId":"2b279d67-459c-4d8f-a83b-44dcaeecb3ac","Phone":"+919116202502","userId":"ef37c8ce6b19aff648c178b0d3afc6bb","Email":"manish1620250122@upgrad.com","Identity":"ef37c8ce6b19aff648c178b0d3afc6bb","Carrier":"JIO 4G","cc":"in","tz":"Asia\/Kolkata"},"s":1643110070,"pg":2,"type":"profile","ep":1643110070,"f":false,"lsl":4,"dsync":true}]
2022-01-25 16:57:53.931 27278-4038/**** D/CleverTap:TEST-5W5-797-K95Z: Sending queue to: https://eu1.clevertap-prod.com/a1?os=Android&t=40400&z=TEST-5W5-797-K95Z&ts=1643110073
2022-01-25 16:57:53.932 27278-4038/**** I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2022-01-25 16:57:53.933 27278-4038/**** I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2022-01-25 16:57:54.034 27278-27278/**** D/SplashScreenActivity: Normal flow, not a deferred launch
2022-01-25 16:57:54.078 27278-27278/**** V/CleverTap:TEST-5W5-797-K95Z: App in background
2022-01-25 16:57:54.078 27278-27278/**** V/CleverTap:TEST-5W5-797-K95Z: Updated session time: 1643110074
2022-01-25 16:57:54.079 27278-3989/**** V/FA: Recording user engagement, ms: 3440
2022-01-25 16:57:54.092 27278-27278/**** V/CleverTap:TEST-5W5-797-K95Z: App in background
2022-01-25 16:57:54.093 27278-27278/**** V/CleverTap:TEST-5W5-797-K95Z: Updated session time: 1643110074

**Comment by manishkummar21** [comment]
@piyush-kukadiya Please check this the log i got

**Comment by piyush-kukadiya** [comment]
@manishkummar21 above logs are not helping. Need Logs after notification arrives.

**Comment by manishkummar21** [comment]
I added the breakpoint also onMessageReceived in our custom FirebaseMessagingService for debugging. its not called after notification was triggered from Dashboard.
@piyush-kukadiya @darshanclevertap

**Comment by manishkummar21** [comment]
> @manishkummar21 above logs are not helping. Need Logs after notification arrives.

As I told in the above comment no notification log also

**Comment by piyush-kukadiya** [comment]
@manishkummar21 You mean message is not getting received only by your custom FirebaseMessagingService class?

**Comment by manishkummar21** [comment]
Not like that, the Previous SDK Version(3.9.1) also we have the custom FirebaseMessagingService class. In this version onMessageReceived as soon as notification is triggered from Dashboard. 

Just we updated the SDK version 4.4.0 with no implementation changes But the onMessageReceived method was not called after notification was triggered from Dashboard and Hence no notification appeared

**Comment by piyush-kukadiya** [comment]
@manishkummar21 Are you using send test approach on dashboard to test notification?

**Comment by piyush-kukadiya** [comment]
I don't feel it's an issue due to sdk upgrade.

**Comment by manishkummar21** [comment]
### **FCM Token Received From Firebase**

 **FCM Token refreshed** - eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6NjM2MDIyMzUxNjA1OmFuZHJvaWQ6YTJiOTlmOGVkNDBiMjUwOSIsImV4cCI6MTY0MzcxODI0NiwiZmlkIjoiZnBXZWcyaE1TM3U3ZlBvNjZ2cDFSRyIsInByb2plY3ROdW1iZXIiOjYzNjAyMjM1MTYwNX0.AB2LPV8wRAIgcOi3e1VVRjotUBQkb-8BibMh56jAh-Bl5K3tuV4ZWQICIE96coJ4FyHkhQyl_uRfBR1S2SCPNgItWrl3G3JZtzCf

 We will register the FCM using this method
 **pushFcmRegistrationId(token, true)**

### In Log


V/CleverTap:TEST-5W5-797-K95Z:  [PushType:FCM] register device token **eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6NjM2MDIyMzUxNjA1OmFuZHJvaWQ6YTJiOTlmOGVkNDBiMjUwOSIsImV4cCI6MTY0MzcxODI0NiwiZmlkIjoiZnBXZWcyaE1TM3U3ZlBvNjZ2cDFSRyIsInByb2plY3ROdW1iZXIiOjYzNjAyMjM1MTYwNX0.AB2LPV8wRAIgcOi3e1VVRjotUBQkb-8BibMh56jAh-Bl5K3tuV4ZWQICIE96coJ4FyHkhQyl_uRfBR1S2SCPNgItWrl3G3JZtzCf**


 V/CleverTap:[:PushProvider:TEST-5W5-797-K95Z]:  [PushType:FCM] getting Cached Token - **eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6NjM2MDIyMzUxNjA1OmFuZHJvaWQ6YTJiOTlmOGVkNDBiMjUwOSIsImV4cCI6MTY0MzcxODI0NiwiZmlkIjoiZnBXZWcyaE1TM3U3ZlBvNjZ2cDFSRyIsInByb2plY3ROdW1iZXIiOjYzNjAyMjM1MTYwNX0.AB2LPV8wRAIgcOi3e1VVRjotUBQkb-8BibMh56jAh-Bl5K3tuV4ZWQICIE96coJ4FyHkhQyl_uRfBR1S2SCPNgItWrl3G3JZtzCf**

V/CleverTap:[:PushProvider:TEST-5W5-797-K95Z]:  [PushType:FCM] FCM token using googleservices.json - **fpWeg2hMS3u7fPo66vp1RG:APA91bEONyaevHRdPsVmRPlEaha8f4nowXZZLj0dwIpactxIKXMpHU4x3_8LvvyqsG0Lkef1IgUTkl2h_q9_xvQClRzYw3wwnnOUmm8m_B9qM8Wjk63TsS4EmCJvicVpc2s1xW6YY7B1**


 V/CleverTap:TEST-5W5-797-K95Z:  [PushType:FCM] register device token **fpWeg2hMS3u7fPo66vp1RG:APA91bEONyaevHRdPsVmRPlEaha8f4nowXZZLj0dwIpactxIKXMpHU4x3_8LvvyqsG0Lkef1IgUTkl2h_q9_xvQClRzYw3wwnnOUmm8m_B9qM8Wjk63TsS4EmCJvicVpc2s1xW6YY7B1**


V/CleverTap:[:PushProvider:TEST-5W5-797-K95Z]:  [PushType:FCM] Cached New Token successfully **fpWeg2hMS3u7fPo66vp1RG:APA91bEONyaevHRdPsVmRPlEaha8f4nowXZZLj0dwIpactxIKXMpHU4x3_8LvvyqsG0Lkef1IgUTkl2h_q9_xvQClRzYw3wwnnOUmm8m_B9qM8Wjk63TsS4EmCJvicVpc2s1xW6YY7B1**

As per the log its the latest cached token registered is **fpWeg2hMS3u7fPo66vp1RG:APA91bEONyaevHRdPsVmRPlEaha8f4nowXZZLj0dwIpactxIKXMpHU4x3_8LvvyqsG0Lkef1IgUTkl2h_q9_xvQClRzYw3wwnnOUmm8m_B9qM8Wjk63TsS4EmCJvicVpc2s1xW6YY7B1**

I searched this user in Clever Tap Dashboard and the token is matched
<img width="1489" alt="Screenshot 2022-01-25 at 6 00 39 PM" src="https://user-images.githubusercontent.com/16359663/150977403-ee2c0129-ca7d-4a74-9a12-9e4b61336f2c.png">

@piyush-kukadiya I am not using the send test approach on the dashboard. For testing Notification, i click on the bell icon
<img width="132" alt="Screenshot 2022-01-25 at 6 02 07 PM" src="https://user-images.githubusercontent.com/16359663/150977595-3be08399-c128-481e-84a1-816c1f4315b6.png">


<img width="1615" alt="Screenshot 2022-01-25 at 6 02 50 PM" src="https://user-images.githubusercontent.com/16359663/150977708-75ec6767-a837-4137-ae78-e0e993cf17bf.png">

<img width="478" alt="Screenshot 2022-01-25 at 6 03 03 PM" src="https://user-images.githubusercontent.com/16359663/150977748-319feb05-4887-49de-bfab-87ac249bb8a1.png">

**Comment by zabolotiny** [comment]
Same issue

**Comment by piyush-kukadiya** [comment]
@zabolotiny What's the actual issue. Please create separate ticket and elaborate for better understanding.

**Comment by zabolotiny** [comment]
@piyush-kukadiya We are trying to send out PUSH campaign to our users. It is working fine for iOS. But for Android no PUSH messages arrive to a user device. I've created support ticket #123331 but there no updates since Thursday after we've provided a debug build from our side.
P.S. Same build successfully receive push messages when we send it through firebase console. Or with help go request to  https://fcm.googleapis.com/fcm/send with same credentials which are added to CleverTap dashboard.

**Comment by piyush-kukadiya** [comment]
@zabolotiny Let me check this internally.

**Comment by zabolotiny** [comment]
Thank you, the issue was solved. 
The problem was connected with wrong notification channel id.
Switching verbose logs helped a lot!
`CleverTapAPI.setDebugLevel(CleverTapAPI.LogLevel.VERBOSE);`
